const Round_2_Data = [
  {
    team: "team1",
    code: "@abcd12",
    images: {
      image1: "/Round_2/Medium/channel.png",
      image2: "/Round_2/Medium/quickheal.png",
      image3: "/Round_2/Medium/shadicom.jpg",
      image4: "/Round_2/Medium/onionbrowser.jpg",
      image5: "/Round_2/Medium/sublime.png",
      image6: "/Round_2/Medium/firebase.png",
      image7: "/Round_2/Medium/digilocker.png",
      image8: "/Round_2/Medium/anydesk.png",
      image9: "/Round_2/Medium/Tanishq.png",
      image10: "/Round_2/Medium/jaguar.png",
      image11: "/Round_2/Easy/Colgate.png",
      image12: "/Round_2/Easy/flipcart.png",
      image13: "/Round_2/Easy/jio.png",
      image14: "/Round_2/Easy/honda.png",
      image15: "/Round_2/Easy/hp.png",
      image16: "/Round_2/Easy/bmw.png",
      image17: "/Round_2/Easy/mtv.png",
      image18: "/Round_2/Easy/pepsi.png",
      image19: "/Round_2/Easy/ferrari.jpg",
      image20: "/Round_2/Easy/pizzahut.png",
      image21: "/Round_2/Easy/Paytmwallet.png",
      image22: "/Round_2/Easy/snapchat.jpg",
      image23: "/Round_2/Easy/brave.png",
      image24: "/Round_2/Easy/Tiktok.png",
      image25: "/Round_2/Easy/ytStudio.png",
    },
  },
  {
    // done
    team: "team2",
    code: "1@efgh3",
    images: {
      image1: "/Round_2/Medium/airindia.png",
      image2: "/Round_2/Easy/android.png",
      image3: "/Round_2/Medium/jaguar.png",
      image4: "/Round_2/Easy/boat.png",
      image5: "/Round_2/Medium/channel.png",
      image6: "/Round_2/Easy/cartoonnetwork.png",
      image7: "/Round_2/Medium/dove.png",
      image8: "/Round_2/Easy/airtel.png",
      image9: "/Round_2/Medium/bhimupi.png",
      image10: "/Round_2/Easy/honda.png",
      image11: "/Round_2/Medium/flutter.png",
      image12: "/Round_2/Easy/ariel.png",
      image13: "/Round_2/Medium/disney.png",
      image14: "/Round_2/Easy/bhajap.png",
      image15: "/Round_2/Medium/anydesk.png",
      image16: "/Round_2/Easy/bmw.png",
      image17: "/Round_2/Medium/bharatpay.png",
      image18: "/Round_2/Easy/boat.png",
      image19: "/Round_2/Medium/ferrari.png",
      image20: "/Round_2/Easy/apple.png",
      image21: "/Round_2/Medium/kalyan.png",
      image22: "/Round_2/Easy/audi.png",
      image23: "/Round_2/Medium/indiannavy.png",
      image24: "/Round_2/Easy/nike.png",
      image25: "/Round_2/Medium/angular.png",
    },
  },
  {
    team: "team3",
    code: "45@ij6k",
    images: {
      image1: "/Round_2/Easy/LG.png",
      image2: "/Round_2/Easy/asus.png",
      image3: "/Round_2/Easy/firebase.png",
      image4: "/Round_2/Medium/malabar.png",
      image5: "/Round_2/Medium/channel.png",
      image6: "/Round_2/Medium/indiannavy.png",
      image7: "/Round_2/Easy/digilocker.png",
      image8: "/Round_2/Medium/lenskart.png",
      image9: "/Round_2/Easy/jiocinema.png",
      image10: "/Round_2/Easy/apple.png",
      image11: "/Round_2/Medium/renault.png",
      image12: "/Round_2/Easy/sublime.png",
      image13: "/Round_2/Easy/nvidia.png", // missing
      image14: "/Round_2/Easy/tatamotors.png",
      image15: "/Round_2/Medium/shell.png",
      image16: "/Round_2/Easy/telegram.png",
      image17: "/Round_2/Medium/unilever.jpg",
      image18: "/Round_2/Easy/twitter.png",
      image19: "/Round_2/Medium/upstock.png",
      image20: "/Round_2/Easy/swiggy.png",
      image21: "/Round_2/Medium/x.png",
      image22: "/Round_2/Easy/nationalgeographic.png",
      image23: "/Round_2/Medium/yamaha.png",
      image24: "/Round_2/Easy/stackoverflow.png",
      image25: "/Round_2/Medium/walmart.png",
    },
  },
  {
    team: "team4", //15
    code: "7lmn@op",
    images: {
      image1: "/Round_2/Easy/pinterest.png",
      image2: "/Round_2/Medium/disney.png",
      image3: "/Round_2/Easy/firebase.png",
      image4: "/Round_2/Medium/flutter.png",
      image5: "/Round_2/Medium/channel.png",
      image6: "/Round_2/Medium/bhimupi.png",
      image7: "/Round_2/Medium/bharatpay.png",
      image8: "/Round_2/Easy/cartoonnetwork.png",
      image9: "/Round_2/Easy/cars24.png",
      image10: "/Round_2/Easy/bmw.png",
      image11: "/Round_2/Medium/dove.png",
      image12: "/Round_2/Medium/ferrari.png",
      image13: "/Round_2/Easy/boat.png",
      image14: "/Round_2/Easy/audi.png",
      image15: "/Round_2/Medium/sugar.png",
      image16: "/Round_2/Medium/starsports.png",
      image17: "/Round_2/Easy/ariel.png",
      image18: "/Round_2/Easy/bhajap.png",
      image19: "/Round_2/Medium/snapdeal.png",
      image20: "/Round_2/Medium/Tanishq.png",
      image21: "/Round_2/Easy/honda.png",
      image22: "/Round_2/Medium/stackoverflow.png",
      image23: "/Round_2/Easy/ucbrowser.png",
      image24: "/Round_2/Medium/basketrobbins.png",
      image25: "/Round_2/Easy/asus.png",
    },
  },
  {
    // done
    team: "team5",
    code: "qr@stuv",
    images: {
      image1: "/Round_2/Easy/zerodha.png",
      image2: "/Round_2/Medium/toyoto.png",
      image3: "/Round_2/Easy/zomato.png",
      image4: "/Round_2/Easy/LG.png",
      image5: "/Round_2/Medium/truecaller.png",
      image6: "/Round_2/Medium/unilever.jpg",
      image7: "/Round_2/Easy/mitsubishi.jpg",
      image8: "/Round_2/Medium/upstock.png",
      image9: "/Round_2/Easy/mtv.png",
      image10: "/Round_2/Medium/x.png",
      image11: "/Round_2/Medium/yamaha.png",
      image12: "/Round_2/Easy/oneplus.png",
      image13: "/Round_2/Medium/walmart.png",
      image14: "/Round_2/Easy/nationalgeographic.png",
      image15: "/Round_2/Easy/onionbrowser.jpg",
      image16: "/Round_2/Medium/youtubestudio.png",
      image17: "/Round_2/Medium/gassistant.png",
      image18: "/Round_2/Easy/paytm.png",
      image19: "/Round_2/Easy/congress.png",
      image20: "/Round_2/Medium/indiannavy.png",
      image21: "/Round_2/Medium/kalyan.png",
      image22: "/Round_2/Medium/jaguar.png",
      image23: "/Round_2/Easy/java.png",
      image24: "/Round_2/Medium/uno.png",
      image25: "/Round_2/Easy/mozillafirefox.png",
    },
  },
  {
    team: "team6",
    code: "wxyz@89",
    images: {
      image1: "/Round_2/Easy/swiggy.png",
      image2: "/Round_2/Easy/target.jpg",
      image3: "/Round_2/Medium/kfc.png",
      image4: "/Round_2/Medium/lenskart.png",
      image5: "/Round_2/Medium/marutisuzuki.png",
      image6: "/Round_2/Easy/tatamotors.png",
      image7: "/Round_2/Easy/telegram.png",
      image8: "/Round_2/Easy/twitter.png",
      image9: "/Round_2/Medium/linux.png",
      image10: "/Round_2/Medium/mercedes-benz.png",
      image11: "/Round_2/Easy/youtube.png",
      image12: "/Round_2/Medium/netscape.png",
      image13: "/Round_2/Easy/YoutubeMusic.png",
      image14: "/Round_2/Medium/playstation.png",
      image15: "/Round_2/Medium/pizzahut.png",
      image16: "/Round_2/Easy/whatsapp.png",
      image17: "/Round_2/Easy/vodaphone.png",
      image18: "/Round_2/Medium/nestle.png",
      image19: "/Round_2/Medium/quickheal.png",
      image20: "/Round_2/Easy/nvidia.png",
      image21: "/Round_2/Easy/adidas.png",
      image22: "/Round_2/Easy/amazon.png",
      image23: "/Round_2/Easy/android.png",
      image24: "/Round_2/Medium/reebok.png",
      image25: "/Round_2/Medium/shell.png",
    },
  },
  {
    team: "team7",
    code: "@abc123",
    images: {
      image1: "/Round_2/Medium/gassistant.png",
      image2: "/Round_2/Medium/firebase.png",
      image3: "/Round_2/Medium/stackoverflow.png",
      image4: "/Round_2/Medium/YoutubeMusic.png",
      image5: "/Round_2/Medium/zerodha.png",
      image6: "/Round_2/Medium/Tanishq.png",
      image7: "/Round_2/Medium/walmart.png",
      image8: "/Round_2/Medium/shadicom.jpg",
      image9: "/Round_2/Medium/jaguar.png",
      image10: "/Round_2/Easy/asus.png",
      image11: "/Round_2/Easy/Superman-Logo.png",
      image12: "/Round_2/Easy/Starbucks.png",
      image13: "/Round_2/Easy/snapchat.jpg",
      image14: "/Round_2/Easy/instagram.png",
      image15: "/Round_2/Easy/Paytmwallet.png",
      image16: "/Round_2/Easy/chatgpt.png", // image missing
      image17: "/Round_2/Easy/batman.png",
      image18: "/Round_2/Easy/sbi.png", // modified // check once
      image19: "/Round_2/Easy/xiomi.jpg",
      image20: "/Round_2/Easy/vscode.jpg",
      image21: "/Round_2/Easy/spotify.png",
      image22: "/Round_2/Easy/pizzahut.png",
      image23: "/Round_2/Easy/volkswagon.png",
      image24: "/Round_2/Easy/adobereader.png",
      image25: "/Round_2/Easy/bookmyshow.png", // modified // check once
    },
  },
  {
    team: "team8",
    code: "def@456",
    images: {
      image1: "/Round_2/Medium/todolist.png",
      image2: "/Round_2/Medium/quickheal.png",
      image3: "/Round_2/Medium/truecaller.png",
      image4: "/Round_2/Medium/shadicom.jpg",
      image5: "/Round_2/Medium/target.jpg",
      image6: "/Round_2/Medium/unilever.jpg",
      image7: "/Round_2/Medium/jaguar.png",
      image8: "/Round_2/Medium/anydesk.png",
      image9: "/Round_2/Medium/YoutubeMusic.png",
      image10: "/Round_2/Medium/sublime.png",
      image11: "/Round_2/Easy/sugar.jpg",
      image12: "/Round_2/Easy/pizzahut.png",
      image13: "/Round_2/Easy/telegram.png",
      image14: "/Round_2/Easy/chrome.jpg",
      image15: "/Round_2/Easy/mercedes-benz.jpg",
      image16: "/Round_2/Easy/honda.png",
      image17: "/Round_2/Easy/facebook.png",
      image18: "/Round_2/Easy/Skype.jpg",
      image19: "/Round_2/Easy/wwf.png",
      image20: "/Round_2/Easy/reebok.png",
      image21: "/Round_2/Easy/youtube.png",
      image22: "/Round_2/Easy/meesho.png",
      image23: "/Round_2/Easy/vscode.jpg",
      image24: "/Round_2/Easy/airtel.png",
      image25: "/Round_2/Easy/zomato.png",
    },
  },
  {
    team: "team9",
    code: "ghi7@89",
    images: {
      image1: "/Round_2/Medium/bharatpay.png",
      image2: "/Round_2/Medium/channel.png",
      image3: "/Round_2/Medium/gassistant.png",
      image4: "/Round_2/Medium/Tanishq.png",
      image5: "/Round_2/Medium/truecaller.png",
      image6: "/Round_2/Medium/bhimupi.png",
      image7: "/Round_2/Medium/quickheal.png",
      image8: "/Round_2/Medium/unilever.jpg",
      image9: "/Round_2/Medium/angular.png",
      image10: "/Round_2/Medium/walmart.png",
      image11: "/Round_2/Easy/honda.png",
      image12: "/Round_2/Easy/hyundai.png",
      image13: "/Round_2/Easy/powerpoint.png",
      image14: "/Round_2/Easy/airtel.png",
      image15: "/Round_2/Easy/ytStudio.png",
      image16: "/Round_2/Easy/gmail.jpg",
      image17: "/Round_2/Easy/batman.png",
      image18: "/Round_2/Easy/youtube.png",
      image19: "/Round_2/Easy/chatgpt.png", // repllcement
      image20: "/Round_2/Easy/telegram.png",
      image21: "/Round_2/Easy/chrome.jpg",
      image22: "/Round_2/Easy/Paytmwallet.png",
      image23: "/Round_2/Easy/phonepe.png",
      image24: "/Round_2/Easy/flipcart.png",
      image25: "/Round_2/Easy/vscode.jpg",
    },
  },
  {
    team: "team10",
    code: "jklm@op",
    images: {
      image1: "/Round_2/Medium/onionbrowser.jpg",
      image2: "/Round_2/Medium/jaguar.png",
      image3: "/Round_2/Medium/bhimupi.png",
      image4: "/Round_2/Medium/nationalgeo.png",
      image5: "/Round_2/Medium/target.jpg",
      image6: "/Round_2/Medium/walmart.png",
      image7: "/Round_2/Medium/playstation.png",
      image8: "/Round_2/Medium/stackoverflow.png",
      image9: "/Round_2/Medium/todolist.png",
      image10: "/Round_2/Medium/digilocker.png",
      image11: "/Round_2/Easy/hp.png",
      image12: "/Round_2/Easy/ytSHORTS.png",
      image13: "/Round_2/Easy/honda.png",
      image14: "/Round_2/Easy/sugar.jpg",
      image15: "/Round_2/Easy/ferrari.jpg",
      image16: "/Round_2/Easy/xiomi.jpg",
      image17: "/Round_2/Easy/wwf.png",
      image18: "/Round_2/Easy/meesho.png",
      image19: "/Round_2/Easy/gmail.jpg",
      image20: "/Round_2/Easy/vi.png",
      image21: "/Round_2/Easy/airtel.png",
      image22: "/Round_2/Easy/pizzahut.png",
      image23: "/Round_2/Easy/youtube.png",
      image24: "/Round_2/Easy/maps.png",
      image25: "/Round_2/Easy/toyota.jpg",
    },
  },
  {
    team: "team11",
    code: "1@23xyz",
    images: {
      image1: "/Round_2/Medium/firebase.png",
      image2: "/Round_2/Medium/mitsubishi.jpg",
      image3: "/Round_2/Medium/target.jpg",
      image4: "/Round_2/Medium/gassistant.png",
      image5: "/Round_2/Medium/flutter.png",
      image6: "/Round_2/Medium/jaguar.png",
      image7: "/Round_2/Medium/Tanishq.png",
      image8: "/Round_2/Medium/quickheal.png",
      image9: "/Round_2/Medium/digilocker.png",
      image10: "/Round_2/Medium/unilever.jpg",
      image11: "/Round_2/Easy/airtel.png",
      image12: "/Round_2/Easy/Starbucks.png",
      image13: "/Round_2/Easy/Olympic.jpg",
      image14: "/Round_2/Easy/zomato.png",
      image15: "/Round_2/Easy/upstock.png",
      image16: "/Round_2/Easy/Skype.jpg",
      image17: "/Round_2/Easy/flipcart.png",
      image18: "/Round_2/Easy/wwf.png",
      image19: "/Round_2/Easy/chrome.jpg",
      image20: "/Round_2/Easy/reliance.jpg",
      image21: "/Round_2/Easy/powerpoint.png",
      image22: "/Round_2/Easy/vi.png",
      image23: "/Round_2/Easy/vlc.png",
      image24: "/Round_2/Easy/bmw.png",
      image25: "/Round_2/Easy/hp.png",
    },
  },
  {
    team: "team12",
    code: "abc@456",
    images: {
      image1: "/Round_2/Medium/flutter.png",
      image2: "/Round_2/Medium/bharatpay.png",
      image3: "/Round_2/Medium/target.jpg",
      image4: "/Round_2/Medium/gassistant.png",
      image5: "/Round_2/Medium/mitsubishi.jpg",
      image6: "/Round_2/Medium/quickheal.png",
      image7: "/Round_2/Medium/Tanishq.png",
      image8: "/Round_2/Medium/stackoverflow.png",
      image9: "/Round_2/Medium/onionbrowser.jpg",
      image10: "/Round_2/Medium/truecaller.png",
      image11: "/Round_2/Easy/vlc.png",
      image12: "/Round_2/Easy/Paytmwallet.png",
      image13: "/Round_2/Easy/phonepe.png",
      image14: "/Round_2/Easy/chrome.jpg",
      image15: "/Round_2/Easy/Superman-Logo.png",
      image16: "/Round_2/Easy/vi.png",
      image17: "/Round_2/Easy/mtv.png",
      image18: "/Round_2/Easy/volkswagon.png",
      image19: "/Round_2/Easy/ferrari.jpg",
      image20: "/Round_2/Easy/netflix.png",
      image21: "/Round_2/Easy/xiomi.jpg",
      image22: "/Round_2/Easy/jiocinema.png",
      image23: "/Round_2/Easy/ytStudio.png",
      image24: "/Round_2/Easy/whatsapp.jpg",
      image25: "/Round_2/Easy/Olympic.jpg",
    },
  },
  {
    team: "team13",
    code: "78@9pqr",
    images: {
      image1: "/Round_2/Medium/todolist.png",
      image2: "/Round_2/Medium/playstation.png",
      image3: "/Round_2/Medium/Tanishq.png",
      image4: "/Round_2/Medium/sublime.png",
      image5: "/Round_2/Medium/channel.png",
      image6: "/Round_2/Medium/firebase.png",
      image7: "/Round_2/Medium/zerodha.png",
      image8: "/Round_2/Medium/unilever.jpg",
      image9: "/Round_2/Medium/target.jpg",
      image10: "/Round_2/Medium/quickheal.png",
      image11: "/Round_2/Easy/instagram.png",
      image12: "/Round_2/Easy/bmw.png",
      image13: "/Round_2/Easy/snapchat.jpg",
      image14: "/Round_2/Easy/boat.png",
      image15: "/Round_2/Easy/reliance.jpg",
      image16: "/Round_2/Easy/batman.png",
      image17: "/Round_2/Easy/facebook.png",
      image18: "/Round_2/Easy/myntra.png",
      image19: "/Round_2/Easy/upstock.png",
      image20: "/Round_2/Easy/chrome.jpg",
      image21: "/Round_2/Easy/adobereader.png",
      image22: "/Round_2/Easy/chatgpt.png", // replacement
      image23: "/Round_2/Easy/flipcart.png",
      image24: "/Round_2/Easy/toyota.jpg",
      image25: "/Round_2/Easy/Superman-Logo.png",
    },
  },
  {
    team: "team14",
    code: "st@uvw4",
    images: {
      image1: "/Round_2/Medium/todolist.png",
      image2: "/Round_2/Medium/mitsubishi.jpg",
      image3: "/Round_2/Medium/bharatpay.png",
      image4: "/Round_2/Medium/truecaller.png",
      image5: "/Round_2/Medium/playstation.png",
      image6: "/Round_2/Medium/shadicom.jpg",
      image7: "/Round_2/Medium/onionbrowser.jpg",
      image8: "/Round_2/Medium/firebase.png",
      image9: "/Round_2/Medium/channel.png",
      image10: "/Round_2/Medium/YoutubeMusic.png",
      image11: "/Round_2/Easy/bookmyshow.png",
      image12: "/Round_2/Easy/Olympic.jpg",
      image13: "/Round_2/Easy/dove.jpg",
      image14: "/Round_2/Easy/swiggy.png",
      image15: "/Round_2/Easy/Skype.jpg",
      image16: "/Round_2/Easy/hp.png",
      image17: "/Round_2/Easy/mtv.png",
      image18: "/Round_2/Easy/toyota.jpg",
      image19: "/Round_2/Easy/telegram.png",
      image20: "/Round_2/Easy/sugar.jpg",
      image21: "/Round_2/Easy/microsoft.png",
      image22: "/Round_2/Easy/vscode.jpg",
      image23: "/Round_2/Easy/myntra.png",
      image24: "/Round_2/Easy/Superman-Logo.png",
      image25: "/Round_2/Easy/bmw.png",
    },
  },
  {
    team: "team15",
    code: "5xy@zab",
    images: {
      image1: "/Round_2/Medium/unilever.jpg",
      image2: "/Round_2/Medium/digilocker.png",
      image3: "/Round_2/Medium/flutter.png",
      image4: "/Round_2/Medium/onionbrowser.jpg",
      image5: "/Round_2/Medium/walmart.png",
      image6: "/Round_2/Medium/todolist.png",
      image7: "/Round_2/Medium/playstation.png",
      image8: "/Round_2/Medium/bharatpay.png",
      image9: "/Round_2/Medium/sublime.png",
      image10: "/Round_2/Medium/channel.png",
      image11: "/Round_2/Easy/myntra.png",
      image12: "/Round_2/Easy/snapchat.jpg",
      image13: "/Round_2/Easy/toyota.jpg",
      image14: "/Round_2/Easy/pepsi.png",
      image15: "/Round_2/Easy/reliance.jpg",
      image16: "/Round_2/Easy/wwf.png",
      image17: "/Round_2/Easy/spotify.png",
      image18: "/Round_2/Easy/zomato.png",
      image19: "/Round_2/Easy/vlc.png",
      image20: "/Round_2/Easy/chatgpt.png", // replacement
      image21: "/Round_2/Easy/hyundai.png",
      image22: "/Round_2/Easy/whatsapp.jpg",
      image23: "/Round_2/Easy/adobereader.png",
      image24: "/Round_2/Easy/honda.png",
      image25: "/Round_2/Easy/meesho.png",
    },
  },
];

export default Round_2_Data;

// @abcd12
// 1@efgh3
// 45@ij6k
// 7lmn@op
// qr@stuv
// wxyz@89
// @abc123
// def@456
// ghi7@89
// jklm@op
// 1@23xyz
// abc@456
// 78@9pqr
// st@uvw4
// 5xy@zab
// 6@cde7f
// g8hi@jk
// lmn@opq
// rstu@vw
// 1vwx@yz
